/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiculoInterfaz;

import Vehiculo.Vehiculo;
import Alarma.Alarma;
import Cinturones.Asiento;
import Luces.TipoLuz;
import parabrisas.Velocidad;
import Radio.Modo;
import Motor.Motor;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import songs.ReproductorSonido;

/**
 *
 * @author AsusVivobook
 */

public class frmVehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmVehiculo.class.getName());
    
    /**
     * Creates new form frmVehiculo
     */
    public frmVehiculo() {
        Vehiculo vehiculo = new Vehiculo();
        initComponents();
    }
    private Vehiculo vehiculo = new Vehiculo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKilometraje = new javax.swing.JButton();
        btnAlarma = new javax.swing.JButton();
        btnParabrisas = new javax.swing.JButton();
        btnEncender = new javax.swing.JButton();
        btnMover = new javax.swing.JButton();
        btnLuces = new javax.swing.JButton();
        btnPuertas = new javax.swing.JButton();
        btnCinturones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEstado = new javax.swing.JTextArea();
        btnAC = new javax.swing.JButton();
        btnRadio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKilometraje.setText("KILOMETRAJE");
        btnKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKilometrajeActionPerformed(evt);
            }
        });

        btnAlarma.setText("ALARMA");
        btnAlarma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlarmaMouseClicked(evt);
            }
        });
        btnAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlarmaActionPerformed(evt);
            }
        });

        btnParabrisas.setText("PARABRISAS");
        btnParabrisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParabrisasActionPerformed(evt);
            }
        });

        btnEncender.setText("ENCENDER");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        btnMover.setText("AVANZAR");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });

        btnLuces.setText("LUCES");
        btnLuces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesActionPerformed(evt);
            }
        });

        btnPuertas.setText("PUERTAS");
        btnPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuertasActionPerformed(evt);
            }
        });

        btnCinturones.setText("CINTURONES");
        btnCinturones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinturonesActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carro.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        btnApagar.setText("APAGAR");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        txtEstado.setEditable(false);
        txtEstado.setColumns(20);
        txtEstado.setRows(5);
        jScrollPane1.setViewportView(txtEstado);

        btnAC.setText("A/C");
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnRadio.setText("RADIO");
        btnRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnApagar)
                        .addGap(37, 37, 37)
                        .addComponent(btnEncender))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnMover)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnLuces)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnPuertas)
                                    .addGap(116, 116, 116))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnKilometraje)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAlarma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnParabrisas)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnRadio)
                                    .addGap(36, 36, 36)
                                    .addComponent(btnAC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCinturones))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMover)
                    .addComponent(btnLuces)
                    .addComponent(btnPuertas))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKilometraje)
                    .addComponent(btnAlarma)
                    .addComponent(btnParabrisas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadio)
                    .addComponent(btnAC)
                    .addComponent(btnCinturones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagar)
                    .addComponent(btnEncender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarEstado(String mensaje) {
    txtEstado.append(mensaje + "\n");
    txtEstado.setCaretPosition(txtEstado.getDocument().getLength());
}
    
    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        String mensaje = vehiculo.apagar();
        mostrarEstado(mensaje); // Esto agrega texto (con append)
        JOptionPane.showMessageDialog(null, "Motor apagado");
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        // TODO add your handling code here:
        String resultado = vehiculo.encender();
        mostrarEstado(resultado);
        JOptionPane.showMessageDialog(null, "Motor encendido.");
        
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        // TODO add your handling code here:
        String mensaje = vehiculo.moverVehiculo(10);
        mostrarEstado("Pongase el cinturon que nos fuimos");
        JOptionPane.showMessageDialog(null, "NOS FUIMOOOOOS.");
        
    }//GEN-LAST:event_btnMoverActionPerformed

    private void btnLucesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesActionPerformed
        // TODO add your handling code here:
        vehiculo.getLuces().LucesDelanteras(Luces.TipoLuz.BAJAS);
        mostrarEstado("Luces delanteras encendidas en modo bajas.");
        JOptionPane.showMessageDialog(null, "LAS LUCES ESTAN ENCENDIDAS");
    }//GEN-LAST:event_btnLucesActionPerformed

    private void btnPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuertasActionPerformed
        // TODO add your handling code here:
        vehiculo.getPuertas().abrirPuerta();
        mostrarEstado("Puertas abiertas.");        
        JOptionPane.showMessageDialog(null, "LAS PUERTAS ESTAN ABIERTAS.");
        
    }//GEN-LAST:event_btnPuertasActionPerformed

    private void btnCinturonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinturonesActionPerformed
        // TODO add your handling code here:
        vehiculo.getCinturones().Abrochar(Asiento.COPILOTO);
        mostrarEstado("Todos los cinturones abrochados.");
        JOptionPane.showMessageDialog(null, "Cinturones abrochados.");
    }//GEN-LAST:event_btnCinturonesActionPerformed

    private void btnAlarmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmaMouseClicked
        // TODO add your handling code here:
        Alarma alarma = vehiculo.getAlarma();
        if (alarma.isAlarmaActiva()) {
            alarma.desactivarAlarma();
            mostrarEstado("Alarma desactivada.");
        } else {
            alarma.activarAlarma();
            mostrarEstado("Alarma activada.");
        }
        JOptionPane.showMessageDialog(null, "Alarma Encendida.");
        
    }//GEN-LAST:event_btnAlarmaMouseClicked

    private void btnParabrisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParabrisasActionPerformed
        // TODO add your handling code here:
        vehiculo.getParabrisas().cambiarVelocidad(parabrisas.Velocidad.LENTO);
        mostrarEstado("Limpia parabrisas activado en velocidad LENTO.");
        JOptionPane.showMessageDialog(null, "limpiando parabrisas.");
        
    }//GEN-LAST:event_btnParabrisasActionPerformed

    private void btnKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKilometrajeActionPerformed
        // TODO add your handling code here:
        vehiculo.getKilometraje().actualizarVelocidad(40); // por ejemplo, 40 km/h
        mostrarEstado("Velocidad actualizada a 40 km/h");
        JOptionPane.showMessageDialog(null, "la velocidad es 40km/h.");
    }//GEN-LAST:event_btnKilometrajeActionPerformed

    private void btnAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlarmaActionPerformed
        // TODO add your handling code here:
        Alarma alarma = vehiculo.getAlarma();
        if (alarma.isAlarmaActiva()) {
            alarma.desactivarAlarma();
            mostrarEstado("Alarma desactivada.");
        } else {
            alarma.activarAlarma();
            mostrarEstado("Alarma activada.");
            JOptionPane.showMessageDialog(null, "Alarma activa.");
        }   
    }//GEN-LAST:event_btnAlarmaActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        // TODO add your handling code here:
        vehiculo.getClimatizacion().encenderAireAcondicinado();
        mostrarEstado("Climatización: aire acondicionado activado.");
        JOptionPane.showMessageDialog(null, "A/C Encendido.");
    }//GEN-LAST:event_btnACActionPerformed

    private void btnRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioActionPerformed
        // TODO add your handling code here:
        vehiculo.getRadio().Encendida(); // Activa radio
        mostrarEstado("Radio encendida.");
        JOptionPane.showMessageDialog(null, "La radio está encendida.");
    
        ReproductorSonido.reproducirSonido("sonidos/radio_on.wav");
    }//GEN-LAST:event_btnRadioActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmVehiculo().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAlarma;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCinturones;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnKilometraje;
    private javax.swing.JButton btnLuces;
    private javax.swing.JButton btnMover;
    private javax.swing.JButton btnParabrisas;
    private javax.swing.JButton btnPuertas;
    private javax.swing.JButton btnRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtEstado;
    // End of variables declaration//GEN-END:variables

    private static class vehiculo {

        private static String apagar() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static String encender() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public vehiculo() {
        }
    }
}
